### ISSUE TITLE
Does not support embedded column?

### ISSUE THREAD

**Issue by seon1-kim** [t-tiger/gorm-bulk-insert#34]
I tried to bulk insert model like below.
```
type Item struct {
  Bucket *Bucket `gorm:"embedded,embedded_prefix:bucket_"`
  ...
}
```

But there's an error like below
```
(/Users/**/go/pkg/mod/github.com/t-tiger/gorm-bulk-insert@v1.3.0/bulk_insert.go:95)
[2020-04-29 13:38:50]  Error 1054: Unknown column 'bucket' in 'field list'
```

gorm-bulk-insert does not support struct that contain embedded column?

**Comment by bombsimon** [comment]
There's no specific handling for embedded fields. Personally, I didn't know about them. 

I did som testing with native `gorm` like this:

```go
func Test_Embedded(t *testing.T) {
	type Bucket struct {
		Name string
	}

	type Item struct {
		Bucket *Bucket `gorm:"embedded,embedded_prefix:bucket_"`
		Size   int
	}

	db, mock, err := sqlmock.New()
	require.NoError(t, err)

	defer db.Close()

	gdb, err := gorm.Open("mysql", db)
	require.NoError(t, err)

	// Easier debugging
	logger := log.New(os.Stdout, "[db DEBUG] ", log.LstdFlags)

	gdb.LogMode(true)
	gdb.SetLogger(logger)

	mock.ExpectBegin()
	mock.ExpectExec(
		"INSERT INTO `items` \\(`size`\\)",
	).WithArgs(
		1024,
	).WillReturnResult(
		sqlmock.NewResult(1, 1),
	)
	mock.ExpectCommit()

	gdb.Create(Item{
		Bucket: &Bucket{
			Name: "my bucket",
		},
		Size: 1024,
	})
```

This gives me the following SQL with bind value `1024`:

```sql
INSERT INTO `items` (`size`) VALUES (?)
```

But... I guess there's more to the `embedded` tag than just omitting it? Because the way I previously omitted fields is with the tag `gorm:"-"`.

I tried the same with `gorm-bulk-insert` which does not ignore the column which is why you get the error.

To me the name is a bit confusing because embedding for me is to include one struct in another like this (which is also how the docs says you should include the `gorm.Model`):

```go
type Bucket struct {
	Name string
}

type Item struct {
	*Bucket
	Size   int
}
```

I don't find much information about the `embedded` tag, could you explain what's suppose to happen with your example? What's the prefix supposed to do? Would it be sufficient to just ignore fields with the `embedded` tag?

**Comment by seon1-kim** [comment]
Example that use `embedded` tag
```
type Item struct {
  Bucket *Bucket `gorm:"embedded,embedded_prefix:bucket_"`
  ...
}

type Bucket struct {
  Name *string
  Value *string
}
```
Item table
```
+------------------------+--------------+------+-----+---------+----------------+
| Field                  | Type         | Null | Key | Default | Extra          |
+------------------------+--------------+------+-----+---------+----------------+
| bucket_name            | varchar(255) | YES  |     | NULL    |                |
| bucket_value           | varchar(255) | YES  |     | NULL    |                |
...
+------------------------+--------------+------+-----+---------+----------------+
```

**Comment by seon1-kim** [comment]
Yeah. I think we just need to ignore the embedded tag.

**Comment by bombsimon** [comment]
Thanks! So I read up about this when I saw your response and found the issue immediately. You're defining your struct tag wrong, you should separate field tags with `;`, not `,`. If you change that, this will work as expected for you.

```diff
- `gorm:"embedded,embedded_prefix:bucket_"`
+ `gorm:"embedded;embedded_prefix:bucket_"`
```
Since this repository uses the underlying mechanism from Gorm to figure out struct fields this will work out of the box.

Here's a test to prove it's working. And just to be clear, this produces the following SQL:

```sql
INSERT INTO `items` (`bucket_name`, `size`) VALUES (?, ?), (?, ?)
-- bind values: [my first bucket 1024 my second bucket 2048]
```

```go
func Test_Embedded(t *testing.T) {
	type Bucket struct {
		Name string
	}

	type Item struct {
		Bucket *Bucket `gorm:"embedded;embedded_prefix:bucket_"`
		Size   int
	}

	db, mock, err := sqlmock.New()
	require.NoError(t, err)

	defer db.Close()

	gdb, err := gorm.Open("mysql", db)
	require.NoError(t, err)

	logger := log.New(os.Stdout, "[db DEBUG] ", log.LstdFlags)

	gdb.LogMode(true)
	gdb.SetLogger(logger)

	mock.ExpectExec(
		"INSERT INTO `items` \\(`bucket_name`, `size`\\)",
	).WithArgs(
		"my first bucket", 1024,
		"my second bucket", 2048,
	).WillReturnResult(
		sqlmock.NewResult(1, 1),
	)

	err = insertObjSet(gdb, []interface{}{
		Item{
			Bucket: &Bucket{
				Name: "my first bucket",
			},
			Size: 1024,
		},
		Item{
			Bucket: &Bucket{
				Name: "my second bucket",
			},
			Size: 2048,
		},
	})

	require.NoError(t, err)
}
```

And btw, thanks for the info about embedded fields, now I've learned something new!

**Comment by bombsimon** [comment]
@seon1-kim I see you gave my response i thumbs up so I guess you got it working? If so, please feel free to close this issue. :)

**Comment by seon1-kim** [comment]
Yeah, It was my fault T.T

But when I insert objects with no Bucket, there's an error.
```
panic: reflect: reflect.flag.mustBeAssignable using unaddressable value [recovered]
        panic: reflect: reflect.flag.mustBeAssignable using unaddressable value

goroutine 20 [running]:
testing.tRunner.func1(0xc00027ce00)
        /usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x48cf5e0, 0xc0004ec3a0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
reflect.flag.mustBeAssignableSlow(0x96)
        /usr/local/go/src/reflect/value.go:247 +0x138
reflect.flag.mustBeAssignable(...)
        /usr/local/go/src/reflect/value.go:234
reflect.Value.Set(0x48b0160, 0xc0002e0fb8, 0x96, 0x48b0160, 0xc0004ec390, 0x16)
        /usr/local/go/src/reflect/value.go:1531 +0x3b
github.com/jinzhu/gorm.(*Scope).Fields(0xc0004c4980, 0xc0004c4980, 0x199, 0x49a9201)
        /Users/**/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/scope.go:119 +0x50a
github.com/t-tiger/gorm-bulk-insert.extractMapValue(0x49a9260, 0xc0002e0f00, 0xc000107e48, 0x1, 0x1, 0x20, 0x48c3aa0, 0x1ec)
        /Users/**/go/pkg/mod/github.com/t-tiger/gorm-bulk-insert@v1.2.1-0.20200121005720-0f3bfc1033ef/bulk_insert.go:111 +0x135
github.com/t-tiger/gorm-bulk-insert.insertObjSet(0xc0004c6820, 0xc00010e800, 0x64, 0x80, 0xc000107e48, 0x1, 0x1, 0x14, 0x0)
        /Users/**/go/pkg/mod/github.com/t-tiger/gorm-bulk-insert@v1.2.1-0.20200121005720-0f3bfc1033ef/bulk_insert.go:34 +0x87
github.com/t-tiger/gorm-bulk-insert.BulkInsert(0xc0004c6820, 0xc00010e800, 0x64, 0x80, 0x3e8, 0xc000107e48, 0x1, 0x1, 0x0, 0x3158e1)
        /Users/**/go/pkg/mod/github.com/t-tiger/gorm-bulk-insert@v1.2.1-0.20200121005720-0f3bfc1033ef/bulk_insert.go:22 +0xda
```

**Comment by seon1-kim** [comment]
model and test code

```
type Item struct {
  Bucket        *Bucket `gorm:"embedded,embedded_prefix:bucket_"`
  ID *string
}

var insertRecords []interface{}
for i := 0; i<= 0; i++ {
 insertRecords = append(insertRecords,
    &Item{
      ID: &resourceId,
      // without bucket
      })
}
err = gormbulk.BulkInsert(db, insertRecords, 1000)
require.Nilf(t, err, "failed to bulk insert: %v", err)
```

**Comment by seon1-kim** [comment]
I wrote test code like your comment. There's an same error
```
func Test_Embedded(t *testing.T) {
	type Bucket struct {
		Name string
	}

	type Item struct {
		Bucket *Bucket `gorm:"embedded;embedded_prefix:bucket_"`
		Size   int
	}

	db, mock, err := sqlmock.New()
	require.NoError(t, err)

	defer db.Close()

	gdb, err := gorm.Open("mysql", db)
	require.NoError(t, err)

	// logger := log.New(os.Stdout, "[db DEBUG] ", log.LstdFlags)

	gdb.LogMode(true)
	// gdb.SetLogger(logger)

	mock.ExpectExec(
		"INSERT INTO `items` \\(`bucket_name`, `size`\\)",
	).WithArgs(
		"my first bucket", 1024,
		"my second bucket", 2048,
	).WillReturnResult(
		sqlmock.NewResult(1, 1),
	)

	err = gormbulk.BulkInsert(gdb, []interface{}{
		Item{
			// without bucket
			Size: 1024,
		},
		Item{
			Bucket: &Bucket{
				Name: "my second bucket",
			},
			Size: 2048,
		},
	}, 1000)

	require.NoError(t, err)
}
```

**Comment by seon1-kim** [comment]
I thinik it's a gorm problem.
`Fields()` in the gorm package do not work properly when model has child struct.
If embedded value is not required, we'll need to put in an empty structure. 
As shown in the example below.
```
func Test_Embedded(t *testing.T) {
	type Bucket struct {
		Name string
	}

	type Item struct {
		Bucket *Bucket `gorm:"embedded;embedded_prefix:bucket_"`
		Size   int
	}

	db, mock, err := sqlmock.New()
	require.NoError(t, err)

	defer db.Close()

	gdb, err := gorm.Open("mysql", db)
	require.NoError(t, err)

	logger := log.New(os.Stdout, "[db DEBUG] ", log.LstdFlags)

	gdb.LogMode(true)
	gdb.SetLogger(logger)

	mock.ExpectExec(
		"INSERT INTO `items` \\(`bucket_name`, `size`\\)",
	).WithArgs(
		"my first bucket", 1024,
		"", 2048,
	).WillReturnResult(
		sqlmock.NewResult(1, 1),
	)

	err = insertObjSet(gdb, []interface{}{
		Item{
			Bucket: &Bucket{
				Name: "my first bucket",
			},
			Size: 1024,
		},
		Item{
			Bucket: &Bucket{},
			Size:   2048,
		},
	})

	require.NoError(t, err)
}
```

I've also thought about putting it in `excludeColumns`, but errors also occur.
```
	err = insertObjSet(gdb, []interface{}{
		Item{
			Bucket: &Bucket{
				Name: "my first bucket",
			},
			Size: 1024,
		},
		Item{
			Bucket: &Bucket{
				Name: "my second bucket",
			},
			Size:   2048,
		},
	}, "Bucket")

	require.NoError(t, err) // ERROR
```

**Comment by bombsimon** [comment]
I haven't looked into this but if this issue persist while using native gorm I don't think there's much we can do in this library. Maybe raise an issue in upstream and close this one?

**Comment by seon1-kim** [comment]
Ok

**Comment by ghost** [comment]
@seon1-kim Hi
docs say this:

```.go
type Author struct {
  Name  string
  Email string
}

type Blog struct {
  ID      int
  Author  Author `gorm:"embedded"`
  Upvotes int32
}

// equals
type Blog struct {
  ID    int64
  Name  string
  Email string
  Upvotes  int32
}
```
 
and when I tried it I got this:

```go
type Author struct {
  Name  string
  Email string
}

type Blog struct {
  ID      int
  Author  Author `gorm:"embedded"`
  Upvotes int32
}

type Blog struct {
  ID    int64
  Author: {
    Name  string
    Email string
  }
  Upvotes  int32
}
```

how can I reach the same as the docs say!?

**Comment by bombsimon** [comment]
If you're talking about how the struct behaves in your Go code that looks correct, the language doesn't care about the struct tag. This is also how the working examples above look.

For any further questions I would suggest upgrading to Gorm 2.0 or file an issue regarding embedded fields in the Gorm repository, this doesn't look like it's related to `gorm-bulk-insert`.
